### PR TITLE
Add support for the Relyze decompiler

### LINKED ISSUE #79: Add Relyze
Tracking issue for adding support for Relyze. Current progress is in #77

### PR DESCRIPTION
**Pull request by stephenfewer**
Hi! This pull request adds Decompiler Explorer support for the Relyze decompiler.

As Relyze is a commercial decompiler you will need a suitable license which I am happy to supply (The license will be a text file you will place in the ./runners/decompiler/tools/relyze/ directory), so just let me know the best point of contact so I can send that on, thanks.

Closes #79

### CODE REVIEW

**Comment by psifertex** [comment]
Thanks very much Stephen! I didn't even consider reaching out given the windows restriction or the potential of using wine, but I'm very much looking forward to testing it, would be happy to have Relyze in the mix.

If you want to shoot me an email to the one on my GH profile I can get the license loaded onto the infrastructure.

Would you also like any special language added to the licensing section? Ilfak and I worked on some [specific language](https://github.com/decompiler-explorer/decompiler-explorer/commit/00495a06581645ffed82af85fb73333a10e8cffe) letting people know what they can and cannot do in terms of running their own version of this service with our standard licenses and if you'd like to clarify your intentions there too (either for or against) that might be helpful.

**Comment by stephenfewer** [comment]
Thanks @psifertex I have sent that email with the required license details.

> Would you also like any special language added to the licensing section? Ilfak and I worked on some [specific language](https://github.com/decompiler-explorer/decompiler-explorer/commit/00495a06581645ffed82af85fb73333a10e8cffe) letting people know what they can and cannot do in terms of running their own version of this service with our standard licenses and if you'd like to clarify your intentions there too (either for or against) that might be helpful.

I will review this and if needed will open up a separate pull request, although at a glance I don't think any change is required.

**Comment by CouleeApps** [comment]
Works on my local test. I'll set up prod and this shortly.

**Comment by CouleeApps** [comment]
Looks like something in the deployment is stopping it from sending the docker images to the worker nodes. We're working on this and hopefully should have it up soon.

**Comment by stephenfewer** [comment]
> Looks like something in the deployment is stopping it from sending the docker images to the worker nodes. We're working on this and hopefully should have it up soon.

Looks like its up and running now, many thanks @CouleeApps 👍

**Comment by psifertex** [comment]
Also, just a heads up that we considered adding Relyze as another default display option but the UI is already a bit crowded. #64 will help with this some but ultimately we want to work on a better UI that lets us tile or otherwise show more results (especially since we're already doing all the work decompiling for all files anyway!)

**Pull request merged**
