### PR TITLE
Add Dewolf decompiler

### LINKED ISSUE #78: Add Dewolf
Tracking issue for adding support for Dewolf. Current progress is in #73

### PR DESCRIPTION
**Pull request by CouleeApps**
Initial version of this, but v0.1.1 has some weird errors that make integration messy:
- [x] Requirements.txt patch because dependencies need an egg name for the delogic repo
- [x] ~There are some exceptions thrown in many many binaries using their latest release: do we want to use main HEAD instead?~ Binja update should have fixed these
- [x] Update binja to 3.1.3615
- [ ] Rebase + merge

Closes #78

### CODE REVIEW

**Comment by CouleeApps** [comment]
CC https://github.com/fkie-cad/dewolf/issues/95

**Comment by steffenenders** [comment]
As pointed out in https://github.com/fkie-cad/dewolf/issues/95, the `requirements.txt` has been updated in v0.1.2

**Comment by CouleeApps** [comment]
Integration now just blocking on rebase + updating remote binja to 3.1.3615-dev

**Comment by steffenenders** [comment]
Hey @CouleeApps , what's the status on this PR?
By the way, we have fixed the issue for dewolf not producing any output when crashing for a subset of functions and made a new release.

**Comment by CouleeApps** [comment]
Good to hear about your release @steffenenders, I'll update this PR when I get a chance. Haven't had much time to look at this PR recently due to the upcoming binja release, but I'll get to it after that goes live.

**Pull request merged**
